### ISSUE TITLE
Question about causeOfDeathStandardized and causeOfDeathText

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/dina-schema#37]
Why do we have under `individualGroup`:
```
individualGroup.causeOfDeathStandardized
individualGroup.causeOfDeathText
```

but under `occurrence`:
`occurrence.isDeathEvent`

Shouldn't they be at the same level under `occurrence`?

**Comment by fredrikolovsson** [comment]
@lisasund @jmenglund please have a look at this question, thanks.

**Comment by lisasund** [comment]
Actually, we discussed this and concluded that "you can only die once", so we put `causeOfDeath` under `individualGroup`. 

We know that we need to extend the model with something between `individualGroup` and `occurrence` quite soon (since many `individualGroups` can be involved in the same `occurrence`), but we haven't had time to go into details about this. We will probably move some attributes around, making it less confusing when this extension is in place...

**Comment by cgendreau** [comment]
Thanks for the clarifications @lisasund  
If I read the definition at https://www.dina-project.net/wiki/Occurrence.0 it is relatively clear.
